server:
  port: 8443
  ssl:
    key-store: 'classpath:ssl/producer-keystore.jks'
    key-store-password: P@SSWORD
    key-password: P@ssw0rd
    trust-store: 'classpath:ssl/producer-truststore.jks'
    trust-store-password: P@ssw0rd
    client-auth: need
    key-store-type: jks
    trust-store-type: jks